import Head from "next/head";
import HeroSection from "components/HeroSection";
import Navbar from "/components/Navbar";


export default function Home() {
	return (
		<>
		<div className=" min-h-screen flex justify-center items-center bg-sea1 bg-fixed">
			{/* <Head>
				<title>Navigation using nextjs and tailwindcss</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
			<Navbar />
			<HeroSection />
			 */}
			<h1 className="font-black text-6xl">WanderSub</h1>
		</div>
		<div className="p-10">
			<h2 className="font-bold text-4xl" >Misssion</h2>
			<p>.............</p>

		</div>
		<div className="bg-sea2 min-h-screen">

		</div>
		</>
	);
};